let products = [
  {
    id: 1,
    name: "Stuffed Chicken",
    image: "./assets/image/1.PNG",
    price: 22,
    amount: 1,
  },
  {
    id: 2,
    name: "Baked chicken wings",
    image: "./assets/image/2.PNG",
    price: 12,
    amount: 1,
  },
  {
    id: 3,
    name: "Salad with salmon",
    image: "./assets/image/3.PNG",
    price: 17,
    amount: 1,
  },
  {
    id: 4,
    name: "Butternut soup",
    image: "./assets/image/4.PNG",
    price: 6,
    amount: 1,
  },
  {
    id: 5,
    name: "Salad with cherry tomatoes",
    image: "./assets/image/5.PNG",
    price: 8,
    amount: 1,
  },
  {
    id: 6,
    name: "Oregano pizza",
    image: "./assets/image/6.PNG",
    price: 24,
    amount: 1,
  },
  {
    id: 7,
    name: "Potatoe pancakes with bacon",
    image: "./assets/image/7.PNG",
    price: 26,
    amount: 1,
  },
  {
    id: 8,
    name: "Chrispy chichken nuggets",
    image: "./assets/image/8.PNG",
    price: 18,
    amount: 1,
  },
  {
    id: 9,
    name: "Bowl of basko",
    image: "./assets/image/9.PNG",
    price: 15,
    amount: 1,
  },
  {
    id: 10,
    name: "Fried chicken nuggets",
    image: "./assets/image/10.PNG",
    price: 18,
    amount: 1,
  },
  {
    id: 11,
    name: "Beef Rendang",
    image: "./assets/image/11.PNG",
    price: 32,
    amount: 1,
  },
  {
    id: 12,
    name: "Sayur Lodeh",
    image: "./assets/image/12.PNG",
    price: 16,
    amount: 1,
  },
  {
    id: 13,
    name: "Spicy Noodles",
    image: "./assets/image/13.PNG",
    price: 19,
    amount: 1,
  },
  {
    id: 14,
    name: "Pasta Carbonara",
    image: "./assets/image/14.PNG",
    price: 27,
    amount: 1,
  },
];

export default products;
